version: '3.9'

services:
  mysql_db4:
    image: mysql:8.0
    container_name: masql8_db4
    ports:
      - "3306:3306"
    #    jdbc:mysql://localhost:3306/db4
    environment:
      MYSQL_ROOT_PASSWORD: 0
      MYSQL_DATABASE: db4
    volumes:
      - mysql_data_db4:/var/lib/mysql


volumes:
  mysql_data_db4: